#!/usr/bin/env bun
// scripts/embed-assets.ts — Generate src/assets.ts from dist/ files

import { resolve, join, extname } from "node:path";
import { readdir } from "node:fs/promises";

const distDir = resolve(import.meta.dirname!, "../dist");
const outFile = resolve(import.meta.dirname!, "../src/assets.ts");

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
};

async function main() {
  const files = await readdir(distDir);
  const entries: string[] = [];

  for (const fileName of files) {
    const filePath = join(distDir, fileName);
    const ext = extname(fileName);
    const mimeType = MIME_TYPES[ext] || "application/octet-stream";
    const content = await Bun.file(filePath).text();

    // Use the route path (/ for index.html, /filename for others)
    const routePath = fileName === "index.html" ? "/" : `/${fileName}`;

    // Escape backticks and ${} in template literal
    const escaped = content
      .replace(/\\/g, "\\\\")
      .replace(/`/g, "\\`")
      .replace(/\$\{/g, "\\${");

    entries.push(
      `  "${routePath}": { content: \`${escaped}\`, mimeType: "${mimeType}" },`
    );
  }

  const output = `// Auto-generated by scripts/embed-assets.ts — DO NOT EDIT
export const assets: Record<string, { content: string; mimeType: string }> = {
${entries.join("\n")}
};
`;

  await Bun.write(outFile, output);
  console.log(`Generated src/assets.ts with ${entries.length} assets`);
}

main();
